### ISSUE TITLE
Cache takes many space in war folder

### ISSUE THREAD

**Issue by SalahAdDin** [linuxdeepin/deepin-wallpapers#2]
I was seeing my space in `Antergos` and i found this:
![problemon](https://user-images.githubusercontent.com/5034215/40007504-a835f8d8-57a5-11e8-9b0a-66687473a089.png)
Searching in internet i saw that that folder is about `deepin-wallpapers`, so, 

How can we clean this space?
Why this app take many space in cache?
Can you solve this using space?

Thank you.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
